apiVersion: v1
kind: Service
metadata:
  name: mywebapp
  namespace: default
  # ให้ label และ selector manage โดย kustomize 
  # labels:
  #   app: mywebapp
spec:
  ports:
  - port: 80
    protocol: TCP
    name: flask
  # selector:
  #   # app: mywebapp
  #   tier: frontend
  type: LoadBalancer