resources:
- ../../base

namespace: devtest


# สร้าง configMap
configMapGenerator:
- envs:
  - config.properties
  name: mywebapp-configmap
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
patches:
- path: replicas.yaml
